// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAooCdWsuysITEQCXUgRzzcZtA8Miq4YNU',
    appId: '1:811950070445:web:984882e638d017f2d74424',
    messagingSenderId: '811950070445',
    projectId: 'bird-weights',
    authDomain: 'bird-weights.firebaseapp.com',
    databaseURL: 'https://bird-weights-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bird-weights.appspot.com',
    measurementId: 'G-LX90WDSFVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGshSEZcPRER8NcvhMRdVue3tuy0sbwBA',
    appId: '1:811950070445:android:24b2638ea7fc16ffd74424',
    messagingSenderId: '811950070445',
    projectId: 'bird-weights',
    databaseURL: 'https://bird-weights-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bird-weights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fm5cs0VD-G4WXZLgLzHmg3xW_jglF3Q',
    appId: '1:811950070445:ios:054738b7b191ecf1d74424',
    messagingSenderId: '811950070445',
    projectId: 'bird-weights',
    databaseURL: 'https://bird-weights-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bird-weights.appspot.com',
    iosClientId: '811950070445-dmekdm2qocq702snq8h1b40navklel1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.birdsWeights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fm5cs0VD-G4WXZLgLzHmg3xW_jglF3Q',
    appId: '1:811950070445:ios:054738b7b191ecf1d74424',
    messagingSenderId: '811950070445',
    projectId: 'bird-weights',
    databaseURL: 'https://bird-weights-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bird-weights.appspot.com',
    iosClientId: '811950070445-dmekdm2qocq702snq8h1b40navklel1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.birdsWeights',
  );
}
